### ISSUE TITLE
Customizable range

### ISSUE THREAD

**Issue by Forhael** [vjdyofficial/Speedo#2]
Hi, I really appreciate your job. It would be nice to have an option to adjust values on the speedometer. For example range up to 50kmh would be a nicer way of using the meter during a bike ride. :)

**Comment by vjdyofficial** [comment]
Sorry for not replying, I'm very busy at the moment. By the way I understand that you will be able to suggest adding a Range Up to 50kmh value in our app. But I see! 

**You will be able to see the range on the meter about 0kmh to 50kmh only while you ride a bike**!
`Tell me if this text is what you are talking about`.

**Comment by Forhael** [comment]
> Sorry for not replying, I'm very busy at the moment. By the way I understand that you will be able to suggest adding a Range Up to 50kmh value in our app. But I see!
> 
> **You will be able to see the range on the meter about 0kmh to 50kmh only while you ride a bike**! `Tell me if this text is what you are talking about`.

Yes, exactly this is what I had in mind.

**Comment by vjdyofficial** [comment]
Thank you for the suggestion. I will do this same as what I do in new airplane speedometer with the range of 600km/h.

**It will take a long time becuase I will going to test it out**
but I am using Kodular App Inventor, so it's easy to do.

- best, vjdy.

**Comment by Forhael** [comment]
Thank you! I'm sure this little change will provide more versatility to your great app :)

**Comment by vjdyofficial** [comment]
You're Welcome! By the way, your suggestion is now added to the app which you can now change the Range Mode to 5 different options. including Boat, Bicycle, Motorcycle, Default, and Airplane. You can access it by clicking the speed button at the side of power button in the next release.

New features will **also added** so stay tuned for that!

Also, I fixed some issues about the **Average Speed** that is still adding while the average is already have value every time the recent speed is more than the average.
_e.g. 40km/h, going back to 38km/h. If it's rises to 39km/h, it's also determined as 39km/h._
